config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :groups, only: [:index, :new, :create, :destroy] do
    resources :entities, only: [:index, :new, :create, :destroy]
  end
  
  # resources :entities, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  has_many :group_entities, foreign_key: :entity_id
  has_many :groups, through: :group_entities, foreign_key: :entity_id
  validates :name, :author, :group, :amount, presence: true

  def date
    date = ''
    date += "#{created_at.day} "
    date += "#{Date::ABBR_MONTHNAMES[created_at.month]} "
    date += created_at.year.to_s
    date
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_entities, foreign_key: :group_id
  has_many :entities, through: :group_entities, foreign_key: :group_id
  validates :name, presence: true
  def total_amount
    total = 0
    entities.each do |t|
      total += t.amount
    end
    total
  end

  def date
    date = ''
    date += created_at.day.to_s
    date += (Date::ABBR_MONTHNAMES[created_at.month]).to_s
    date += created_at.year.to_s
    date
  end
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
  validates :entity, uniqueness: { scope: :group, message: 'already exists in this category' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'author_id'
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # def after_sign_in_path_for(_resource)
  #   home_path
  # end

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  # end
  def require_login
    return if user_signed_in?

    redirect_to root_path
  end

  def after_sign_in_path_for(_user)
    groups_path
  end

  def after_sign_out_path_for(_user)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
    # @group_entities = Entity.where(group: @group)
  end

  def new
    @new_entity = Entity.new
    @group = Group.find(params[:group_id])
    @user_groups = Group.where(user: current_user)
  end

  def create
    # @group = Group.find(params[:group_id])
    # @entity = @group.entities.new(name: entity_params[:name],
    #   amount: entity_params[:amount], author_id: current_user.id)
    entity = Entity.create(name: entity_params[:name], author_id: current_user.id, amount: entity_params[:amount])
    return unless entity.save

    GroupEntity.create(entity_id: entity.id, group_id: params[:group])
    flash[:notice] = 'Transaction created successfully'
    redirect_to group_entities_path
    # if @entity.save
    #   flash[:notice] = 'Transaction is completed'
    #   redirect_to group_entities_path(@group)
    # else
    #   flash[:notice] = 'Invalid Transaction!'
    # end
  end

  def destroy
    @transaction = Entity.find(params[:id])

    return unless @transaction.destroy

    flash[:success] = 'Transaction deleted successfully.'
    redirect_to group_entities_path(params[:group_id])
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :author_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # before_action :require_login
  def index
    # @groups = Group.where(author_id: current_user)
    @groups = Group.all.order(created_at: :desc).includes(:entities)
  end

  def new
    @group = Group.new
  end

  # def create
  #   @new_group = Group.new(group_params)
  #   return unless @new_group.save

  #   flash[:success] = 'Category created successfully.'
  #   redirect_to groups_path
  # end

  def create
    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = 'Category created successfully'
      redirect_to groups_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    return unless @group.destroy

    flash[:success] = 'Category deleted successfully.'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :author_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_user)
    new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/entities/index.html.erb
<header class="page-header">
<h1>Transactions</h1>
</header>
<section>
<div class="top-card">
<span class="primary-text">Total amount</span>
<span class="sec-text"><%= @group.total_amount %></span>
</div>
<div class="cards-container transactions-container">
<%= @entities.each do |entity| %>
<div class="card">
<div class="column">
<span class="primary-text"><%= entity.name %></span>
<span class="date-stamp"><%= entity.date%></span>
</div>
<div class="column last-col">
<span class="sec-text"><%= entity.amount%></span>
<span><%= button_to image_tag(), group_path(group.id), method: :delete, class: "del-group-btn btn-icon"%></span>
</div>
</div>
<% end %>
<%= link_to "ADD TRANSACTION", new_group_entity_path(@group), class: "btn-add" %>
 </div>
</section>

app/views/entities/new.html.erb
<header class="page-header">
<h1>New Transaction</h1>
</header>
<section class="form-wrapper" id="new-category-form">
<%= form_for @new_entity, url: group_entities_path, html: { method: :post } do |f| %>
 <div class="field">
 <%= f.text_field :name, placeholder: "Name" %>
 </div>
 <div class="field">
 <%= f.number_field :amount, placeholder: "Amount" %>
 </div>
 <div class="field">
  <%= f.collection_select :group_id, @user_groups, :id, :name %>
 </div> 
 <%= f.hidden_field :author_id, value: current_user.id %>
 <div class="field" >
<%= f.submit :ADD, class: 'btn-add'%>
</div>
<% end %>
</section>

app/views/groups/index.html.erb
<header class="page-header">
<%# <span><%= button_to image_tag('hamburger4.png'), method: :delete, class: "del-group-btn btn-icon"%>
<%# <i class="fa fa-bars" aria-hidden="true"></i> %>
<h1>Categories</h1>
<span><%= button_to image_tag('search.jpg'), method: :delete, class: "del-group-btn btn-icon"%></span>
</header>
<section>
 <div class="cards-container">
   <% @groups.each do |group| %>
   <a class="card-link-wrapper" href="<%= group_entities_path(group) %>">
   <div class="card">
   <div class="img-plchldr column"><img src="<%= group.icon %>"></div>
   <div class="column">
   <span><%= group.name %></span>
   <span class="date-stamp"><%= group.date %></span>
   </div>
   <div class="column last-col">
   <span class="sec-text"><%= group.total_amount %></span>
   <%# <span><%= button_to image_tag(), group_path(group.id), method: :delete, class: "del-group-btn btn-icon"%>
   </div>
 </div>
 </a>
 <% end %>
 <%= link_to "ADD CATEGORY", new_group_path, class: "btn-add" %>
 </div>
</section>

app/views/groups/new.html.erb
<header class="page-header">
<h1>New Category</h1>
</header>
<section class="form-wrapper" id="new-category-form">
<%= form_for @group, url: groups_path, html: { method: :post } do |f| %>
 <div class="field">
 <%= f.text_field :name, placeholder: "Name" %>
 </div>
 <div class="field">
 <%= f.text_field :icon, placeholder: "Icon URL", class: "last-input" %>
 </div>
 <div class="field" >
<%= f.submit :CREATE, class: "btn-add" %>
</div>
<% end %>
</section>

app/views/home/index.html.erb
<section class="First-page">
<header>
<h1 class="header">Budget App</h1>
</header>
<nav>
 <%= link_to "SIGN IN", new_user_session_path, class: "btn blue-btn" %><br /><br>
 <%= link_to "SIGN UP", new_user_registration_path, class: "btn gray-btn" %>
</nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>